### ISSUE TITLE
index out of range [0] with length 0

### ISSUE THREAD

**Issue by rebelice** [PingCAP-QE/clustered-index-rand-test#38]
Usage:
```
func main() {
	state := sqlgen.NewState()
	state.StoreConfig(sqlgen.ConfigKeyIntMaxTableCount, 200)
	state.SetWeight(sqlgen.IndexDefinitions, 50)
	state.SetWeight(sqlgen.PartitionDefinition, 100)

	gen := sqlgen.NewGenerator(state)

	for i := 0; i < 10000; i++ {
		ss := gen()
	}
}
```
Stack
```
goroutine 1 [running]:
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.(*Table).GetRandUniqueIndexForPointGet.func1(0xc0002f9680, 0x1)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/db_retriever.go:275 +0x71
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.(*Table).FilterIndexes(0xc00022cb40, 0x55d0b8, 0xc0000a68e0, 0x4b9225, 0xc00007c150)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/db_retriever.go:136 +0xda
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.(*Table).GetRandUniqueIndexForPointGet(0xc00022cb40, 0x2)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/db_retriever.go:274 +0x3b
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.glob..func46(0xc00018a410, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/start.go:627 +0x145
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.NewFn.func1(0xc00018a410, 0xc00007c3f0, 0xc00001a5d4)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:39 +0x36
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc000010780, 0xc00001a5d4, 0xa, 0x1, 0x1, 0x3, 0xc00018a410, 0x553d51, 0x5)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.And.func1(0xc00018a410, 0xc00007c3f0, 0x5539ba)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_lib.go:33 +0x156
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc000395600, 0x5539ba, 0x3, 0x1, 0x1, 0x3, 0xc00018a410, 0x5b, 0xc0004dec40)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.NewFn.func1(0xc00018a410, 0xc00007c3f0, 0xc00001a724)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:39 +0x85
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc000010800, 0xc00001a724, 0xc, 0x1, 0x1, 0x3, 0xc00018a410, 0x4c, 0x80)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Or.func1(0xc00018a410, 0xc00007c3f0, 0x55392b)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_lib.go:49 +0x105
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc0004dec20, 0x55392b, 0x2, 0x1, 0x1, 0x3, 0xc00018a410, 0x47, 0xc0004debd0)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.NewFn.func1(0xc00018a410, 0xc00007c3f0, 0xc000018a84)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:39 +0x85
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc000010810, 0xc000018a84, 0x10, 0x1, 0x1, 0x3, 0xc00018a410, 0x34, 0x40)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Or.func1(0xc00018a410, 0xc00007c3f0, 0x55392b)
        /home/yang/go/pkg/mod/github.com/!pin!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_lib.go:49 +0x105
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc0004debb0, 0x55392b, 0x2, 0x1, 0x1, 0x3, 0xc00018a410, 0x2f, 0xc0004deba0)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.NewFn.func1(0xc00018a410, 0xc00007c3f0, 0xc00001a754)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:39 +0x85
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc000010820, 0xc00001a754, 0x5, 0x1, 0x1, 0x3, 0xc00018a410, 0x30, 0x1)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.And.func1(0xc00018a410, 0xc00007c3f0, 0x5539ba)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_lib.go:33 +0x156
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc000395500, 0x5539ba, 0x3, 0x1, 0x1, 0x3, 0xc00018a410, 0x21, 0xc0004deb40)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.NewFn.func1(0xc00018a410, 0xc00007c3f0, 0xc00001a7e4)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:39 +0x85
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc000010870, 0xc00001a7e4, 0xb, 0x2, 0x1, 0x3, 0xc00018a410, 0x13, 0x20)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Or.func1(0xc00018a410, 0xc00007c3f0, 0x55392b)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_lib.go:49 +0x105
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc0004deb20, 0x55392b, 0x2, 0x1, 0x1, 0x3, 0xc00018a410, 0xe, 0xc0004deb10)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.NewFn.func1(0xc00018a410, 0xc00007c3f0, 0xc00001a844)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:39 +0x85
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.Fn.Eval(0xc0000108a0, 0xc00001a844, 0x5, 0x1, 0x1, 0x3, 0xc00018a410, 0x0, 0x0)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/generator_types.go:78 +0x277
github.com/PingCAP-QE/clustered-index-rand-test/sqlgen.NewGenerator.func1(0x581a18, 0xc00000e018)
        /home/yang/go/pkg/mod/github.com/!ping!c!a!p-!q!e/clustered-index-rand-test@v0.0.0-20210526064708-5c01a048c37f/sqlgen/start.go:17 +0x4e
main.main()
        /home/yang/PingCAP/partition_rand_tests/main.go:17 +0x2e7
g
```

**Comment by tangenta** [comment]
The bug has been fix in https://github.com/PingCAP-QE/clustered-index-rand-test/commit/3e1cceed9e2eda4774ddfcfe4ac621645ebe9ff5. PTAL @rebelice
